import Head from 'next/head'
import Link from 'next/link'

import styles from '@/styles/home.module.scss'
import { fetcher } from '@/utils/index'

type HomeProps = {
  data: any[]
  error: any
}

export const getStaticProps = async () => {
  const props: HomeProps = await fetcher('entries/hero')

  return {
    props,
  }
}

export default function Home({ data, error }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ada POC Web</h1>
        <section>
          <ul>
            {error && <p>{error.message}</p>}
            {data &&
              data.length > 0 &&
              data.map((heroEntry: any, index: number) => (
                <li key={index}>
                  <Link
                    href={`/hello-mama/${heroEntry.uid}?utm_source=${heroEntry.utm_source}`}
                  >
                    <a>{heroEntry.utm_source}</a>
                  </Link>
                </li>
              ))}
            {!error && data.length === 0 && <p>There is no entries to show</p>}
          </ul>
        </section>
      </main>
    </div>
  )
}
