import Head from 'next/head'
import Link from 'next/link'

import styles from '@/styles/home.module.scss'
import { fetcher } from '@/utils/index'
import { HeroCMS } from '@/types'

type HomeProps = {
  heroEntries?: HeroCMS[]
}

export const getStaticProps = async () => {
  const heroEntries = await fetcher('entries/hero')

  return {
    props: {
      heroEntries,
    },
  }
}

export default function Home({ heroEntries }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ada POC Web</h1>
        <section>
          {heroEntries && (
            <ul>
              {heroEntries.map((heroEntry: any, index: number) => (
                <li key={index}>
                  <Link
                    href={`/hello-mama/${heroEntry.uid}?utm_source=${heroEntry.utm_source}`}
                  >
                    <a>{heroEntry.utm_source}</a>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </section>
      </main>
    </div>
  )
}
