import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'

import styles from '@/styles/home.module.scss'
import { fetcher } from '@/utils/index'

type HomeProps = {
  data: any[]
  error: any
}

export const getStaticProps = async () => {
  const props: HomeProps = await fetcher('entries/hero')

  return {
    props,
  }
}

export default function Home({ data, error }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script id="analytics">
        {`!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="vZClG2DDsxYNT6PrtQhDFcqRQmbvYs5i";analytics.SNIPPET_VERSION="4.13.2";
          analytics.load("mV5doQT9HcNzTdo5stXjbS4YaX4sT2Ic");
          analytics.page();
        }}();`}
      </Script>

      <main className={styles.main}>
        <h1 className={styles.title}>Ada POC Web</h1>
        <section>
          <ul>
            {error && <p>{error.message}</p>}
            {data &&
              data.length > 0 &&
              data.map((heroEntry: any, index: number) => (
                <li key={index}>
                  <Link
                    href={`/hello-mama/${heroEntry.uid}?utm_source=${heroEntry.utm_source}`}
                  >
                    <a>{heroEntry.utm_source}</a>
                  </Link>
                </li>
              ))}
            {!error && data.length === 0 && <p>There is no entries to show</p>}
          </ul>
        </section>
      </main>
    </div>
  )
}
