import { GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import { fetcher } from '@/utils/index'
import { Layout } from '@/components/layout/layout'
import styles from '@/styles/hello-mama.module.scss'
import { HeroCMS } from '@/types'

type HelloMamaProps = {
  data: HeroCMS
  error: string
}

export const getStaticPaths = async () => {
  const response = await fetcher('entries/hero')
  const { data, error } = response
  const paths = data.map((heroEntry: any) => {
    return {
      params: { entry_uid: heroEntry.uid },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  if (context && context.params) {
    const entry_uid = context.params.entry_uid
    const response = await fetcher(`entry/hero/${entry_uid}`)
    const { data, error } = response
    return {
      props: { data, error },
    }
  }
  return { props: {} }
}

export default function HelloMama({ data, error }: HelloMamaProps) {
  return (
    <div>
      {data && (
        <Layout options={{ showBackButton: false }}>
          <Head>
            <title>{data.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <h1 className={styles.heading}>{data.title}</h1>
            <Image
              src={
                data.image?.href ? data.image.href : '/images/happy_mama_2.jpeg'
              }
              width={1373}
              height={898}
              alt={data.title}
              layout="intrinsic"
            />
            <div className={styles.actions}>
              <Link href="/natural-language-form">
                <a className={`button primary ${styles.actions}`}>
                  {data.cta_button}
                </a>
              </Link>
            </div>
          </main>
        </Layout>
      )}
    </div>
  )
}
